name: CD

on:
  # Versioned Tags
  push:
    tags:
      - "v*.*.*"

jobs:
  # Build and test everything
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up the GoLang environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Download all the tools used in the steps that follow
      - name: Set up Tools
        run: |
          make get-tools

      # Run all the unit-tests
      - name: Test
        run: |
          make test

      # Build all the binaries for upload
      - name: Build Binaries
        run: |
          make dist

      # Release binaries
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/go-sudoku*
